@extends('admin.layouts.app')

@section('content')
    <style>
        :root {
            --primary-gradient: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%);
            --bg-main: #f8fafc;
            --text-main: #1e293b;
            --text-muted: #64748b;
        }

        .content-wrapper { background-color: var(--bg-main); font-family: 'Inter', sans-serif; }
        .premium-page-header { padding: 1.5rem 0; background: #fff; border-bottom: 1px solid #e2e8f0; margin-bottom: 2rem; }
        .page-title { font-size: 1.75rem; font-weight: 800; color: var(--text-main); margin: 0; }
        .card-premium { border: none; border-radius: 1rem; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); overflow: hidden; background: #fff; margin-bottom: 2rem; }
        .detail-label { font-size: 0.75rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 0.25rem; }
        .detail-value { font-size: 1rem; font-weight: 600; color: var(--text-main); }
        .table-premium thead th { background: #f8fafc; text-transform: uppercase; font-size: 0.7rem; font-weight: 700; color: var(--text-muted); border: none; padding: 1rem; }
        .table-premium td { padding: 1rem; font-size: 0.875rem; border-color: #f1f5f9; vertical-align: middle; }
        .badge-soft-info { background: #eff6ff; color: #2563eb; }
        .summary-box { background: #f8fafc; border-radius: 0.75rem; padding: 1.5rem; }
    </style>

    <div class="content-wrapper">
        <div class="premium-page-header">
            <div class="container-fluid">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h1 class="page-title">Session Details</h1>
                        <p class="text-muted mb-0 small">Session #{{ $session->id }} | Generated by {{ $session->creator->name ?? 'System' }}</p>
                    </div>
                    <div class="d-flex" style="gap: 10px;">
                        <a href="{{ route('admin.inventory.inbound_history.download-prn', $session->id) }}" class="btn btn-dark px-4" style="border-radius: 0.5rem; font-weight: 600;">
                            <i class="fas fa-barcode mr-2"></i>Download PRN
                        </a>
                        <a href="{{ route('admin.inventory.inbound_history.index') }}" class="btn btn-outline-secondary px-4" style="border-radius: 0.5rem; font-weight: 600;">
                            <i class="fas fa-arrow-left mr-2"></i>Back
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <section class="content">
            <div class="container-fluid">
                <!-- Header Info -->
                <div class="card card-premium">
                    <div class="card-body p-4">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="detail-label">Session ID</div>
                                <div class="detail-value text-primary font-weight-bold">SESSION-{{ $session->id }}</div>
                            </div>
                            <div class="col-md-3">
                                <div class="detail-label">Date</div>
                                <div class="detail-value">{{ \Carbon\Carbon::parse($session->packing_date ?? $session->created_at)->format('d M Y') }}</div>
                            </div>
                            <div class="col-md-3">
                                <div class="detail-label">Total Unique Products</div>
                                <div class="detail-value">{{ $items->count() }} Variants</div>
                            </div>
                            <div class="col-md-3">
                                <div class="detail-label">Total Boxes Generated</div>
                                <div class="detail-value text-success font-weight-bold">{{ $items->sum('box_quantity') }} Boxes</div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Items Table -->
                <div class="card card-premium">
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-premium mb-0">
                                <thead>
                                    <tr>
                                        <th class="pl-4">Design / Details</th>
                                        <th>Style / Fitting</th>
                                        <th>Warehouse / Rack</th>
                                        <th>Size & Color</th>
                                        <th class="text-center">Total Boxes</th>
                                        <th class="text-center">Pcs/Box</th>
                                        <th class="text-center">Total Qty</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($items as $item)
                                    <tr>
                                        <td class="pl-4">
                                            <div class="font-weight-bold text-dark">
                                                @if($item->newProduct && $item->newProduct->series)
                                                    <span class="text-muted mr-1">{{ $item->newProduct->series->name }}</span>
                                                @endif
                                                {{ $item->newProduct->name_of_garment ?? 'N/A' }}
                                            </div>
                                            <div class="small text-muted">#{{ $item->newProduct->design_number ?? 'N/A' }}</div>
                                        </td>
                                        <td>
                                            <div class="text-dark">{{ $item->newProduct->pattern->name ?? 'N/A' }}</div>
                                            <div class="small text-muted">{{ $item->newProduct->fitting->name ?? 'N/A' }}</div>
                                        </td>
                                        <td>
                                            <div class="text-dark">
                                                {{ $item->newRack->storeroom->name ?? 'N/A' }}
                                            </div>
                                            <div class="small text-muted">Rack: {{ $item->newRack->name ?? 'N/A' }}</div>
                                        </td>
                                        <td>
                                            <div class="badge badge-soft-info">{{ $item->newSizeSet->name ?? 'N/A' }}</div>
                                            <div class="small text-muted mt-1">{{ $item->newColor->name ?? 'N/A' }}</div>
                                        </td>
                                        <td class="text-center font-weight-bold text-primary">{{ $item->box_quantity }}</td>
                                        <td class="text-center">{{ $item->pieces_per_box }}</td>
                                        <td class="text-center font-weight-bold text-success">{{ $item->box_quantity * $item->pieces_per_box }} Pcs</td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="7" class="text-center py-4 text-muted">No items found for this session.</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection
